---
title: "Awards"
---

2026 –	Selected for the **rOpenSci Champions Program2026** 

2025 –	**Best Poster Award** in the category “tool” granted to **“EV-Net”** by the International Society of Computational Biology NetBio CoSI at the ISMB/ECCB 2025 conference in Liverpool, UK. 

2025 –	**Travel fellowship** granted by the Twinning Project Extracellular Vesicles in Clinical Applications (EVCA) to attend the ISEV2025 conference in Vienna, Austria. 

2024 –	**EMBO scientific exchange grant** for a visit to the Marseille Medical Genetics Research Center (3 months). 
2024 –	**Travel fellowship** granted by the Twinning Project Extracellular Vesicles in Clinical Applications (EVCA) to attend the RECOMB2024 conference in Cambridge, USA. 

2023 –	**Travel fellowship** and registration fee waiver for the International Society of Computational Biology Student Council Symposium and main event ISMBECCB2023 . 

2022 –	**PhD fellowship** “iNOVA4Health – Translational Medicine programme”. 

2019 –	**Best Poster Award** at the “BioTicks2019: The challenge of tick control” conference, with the poster: “Bartonella spp. in stray cats and questing ticks from Portugal mainland”. 

2019 –	**Travel fellowship and registration fee waiver** granted by Quest Diagnosis (USA) to attend the “9th International Conference on Bartonella as Emerging Pathogens” meeting in Paris, France.  

2017 –	**Scientific exchange fellowship** “Movilización Nacional e Internacional en Ciencia, Tecnología e Innovación 2016-04” by the Peruvian Foundation for Science and Technology for a 3-month internship at the IHMT in Lisbon, Portugal. 

2008 –	**Excellence Award (Valedictorian Title)** for achieving the top rank among all students throughout my high school years 